// <auto-generated />
namespace project1.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class DBproduct : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(DBproduct));
        
        string IMigrationMetadata.Id
        {
            get { return "202307131043106_DBproduct"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
